### ISSUE TITLE
Mejorar visualización porcentaje/horas en la progress-bar

### ISSUE THREAD

**Issue by soulasvalentin** [soulasvalentin/DevOpsDashboard#2]
![image](https://user-images.githubusercontent.com/11997704/50852212-b1f4af80-135d-11e9-93d8-3d09310ce688.png)

Si alguna de las 2 barras es muy corta se corta el label.
Analizar que solución se le puede dar

**Comment by Martin25zxc** [comment]
En lugar de utilizar dos barras se utiliza solo una con un label centrado con el siguiente formato>
PorcentajeCompletado.(HsCompletadas/HorasTotalesEstimadas)
También se añadió la característica que si WorkCompletedPercentaje es 100 el label se mostrara con el texto "Completado"
![image](https://user-images.githubusercontent.com/23322718/51092053-06d76200-1772-11e9-86b1-39c1ac4a2476.png)
